import { useEffect, useState } from "react";
import { getArticles, getModelInfo } from "../api/client.js";
import { useNavigate } from "react-router";

const ArticlesList = () => {
  const [articles, setArticles] = useState([]);
  const [modelInfo, setModelInfo] = useState({});
  const navigate = useNavigate();

  useEffect(() => {
    const fetchArticles = async () => {
      const data = await getArticles();
      setArticles(data);
    };
    const fetchModelInfo = async () => {
      const info = await getModelInfo();
      setModelInfo(info);
    };
    fetchArticles();
    fetchModelInfo();
  }, []);

  return (
    <div className="bounce-in p-4 flex flex-col justify-start items-center bg-black text-white min-h-screen">
      <div className="m-30">
        <h1 className=" playfair font-bold text-4xl max-w-150">Articles</h1>
        {modelInfo.model && (
          <p className="text-sm font-extralight inter text-neutral-400">
            Generated by {modelInfo.model}
          </p>
        )}
      </div>
      <ul className=" flex flex-col gap-4 max-w-150 mb-30">
        {articles.map((article) => (
          <li
            onClick={() => navigate(`/articles/${article.id}`)}
            key={article.id}
            className="cursor-pointer hover:opacity-80 transition-opacity"
          >
            <h2 className="text-2xl">{article.title}</h2>
            <p className="leading-loose text-sm font-extralight inter text-yellow-500">
              {article.content.split(".")[0]}...
            </p>
          </li>
        ))}
        {articles.length === 0 && (
          <p className="text-sm font-extralight inter text-neutral-400">
            Database not running.
          </p>
        )}
      </ul>
    </div>
  );
};

export default ArticlesList;
